# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: '3'
services:

  app:
    image: go-gin-sample-app-test:0.0.0
    environment: &environment
      - ENVIRONMENT=test
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
      args:
        env: test
        version: 0.0.0
    volumes:
      - .:/usr/src
